spring:
  security.enable-csrf: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-176-34-105-15.eu-west-1.compute.amazonaws.com/d8jtjtgo53tasc
    username: sbhcjsoywaxabt
    password: "e9ca04b0c16d5c5b2ac20dfd48fdcfb6e97222bc28b157c41300b6be13720812"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
